import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://rsms.me/inter/inter.css" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to your <a href="https://mobility-blueprint.com">Mobility Blueprint</a>
        </h1>

        <p className={styles.description}>
          Get started
        </p>

        <div className={styles.grid}>
          <a href="/conditioning" className={styles.card}>
            <h2>Conditioning &rarr;</h2>
            <p>Fascial conditioning exercises for 5 directions of movement.</p>
          </a>

          <a href="/renewal" className={styles.card}>
            <h2>Renewal &rarr;</h2>
            <p>Fascial renewal exercises for all 5 directions of movement</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Daily 10s &rarr;</h2>
            <p>5 conditioning exercises and 5 renewal exercises randomly generated for a quick daily routine without having to think about it</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Joint Mobility &rarr;</h2>
            <p>
              Circular mobility exercises.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
